
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javaspringboot
 */
public class Main extends javax.swing.JFrame {
    
    public static ArrayList<String> productNames = new ArrayList<>();
    public static double[] prices = new double[100];
    public static HashMap<String,Integer> stockProducts = new HashMap<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductBtn = new javax.swing.JButton();
        listInventoryBtn = new javax.swing.JButton();
        buyProductBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        lookProductForNameBtn = new javax.swing.JButton();
        getOutWithFinalTicketBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addProductBtn.setText("Agregar Producto");
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });

        listInventoryBtn.setText("Listar Inventario");
        listInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listInventoryBtnActionPerformed(evt);
            }
        });

        buyProductBtn.setText("Comprar producto");
        buyProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyProductBtnActionPerformed(evt);
            }
        });

        reportsBtn.setText("Mostar estadisticas");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        lookProductForNameBtn.setText("Buscar producto por nombre");

        getOutWithFinalTicketBtn.setText("Salir con ticket final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getOutWithFinalTicketBtn)
                    .addComponent(lookProductForNameBtn)
                    .addComponent(reportsBtn)
                    .addComponent(buyProductBtn)
                    .addComponent(addProductBtn)
                    .addComponent(listInventoryBtn))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(addProductBtn)
                .addGap(18, 18, 18)
                .addComponent(listInventoryBtn)
                .addGap(18, 18, 18)
                .addComponent(buyProductBtn)
                .addGap(18, 18, 18)
                .addComponent(reportsBtn)
                .addGap(18, 18, 18)
                .addComponent(lookProductForNameBtn)
                .addGap(18, 18, 18)
                .addComponent(getOutWithFinalTicketBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtnActionPerformed
        
        String nameProduct = JOptionPane.showInputDialog(rootPane, "Ingrese el nombre del producto", "Ventana", JOptionPane.QUESTION_MESSAGE); 
        if(nameProduct == null) return;
        
        if(productNames.contains(nameProduct)){
            JOptionPane.showMessageDialog(rootPane, "El producto con nombre " + nameProduct + "ya esta registrado.", "Error", HEIGHT);
        }

        Double price = this.readDouble("Ingrese el precio del producto", "Ventana", JOptionPane.QUESTION_MESSAGE);            
        if(price == null) return;

        Integer stock = this.readInteger("Ingrese el stock del producto", "Ventana", JOptionPane.QUESTION_MESSAGE);
        if(stock == null) return;
        
        addProduct(nameProduct,price,stock);
        
    }//GEN-LAST:event_addProductBtnActionPerformed

    
    // Utilitary methods
    public void addProduct(String nameProduct,double price, int stock){
        
        productNames.add(nameProduct);
        prices[productNames.size()-1] = price;
        stockProducts.put(nameProduct, stock);
        
        expandPrices();
        JOptionPane.showMessageDialog(rootPane, "Se ha agregado el producto exitosamente.", "Exito", JOptionPane.PLAIN_MESSAGE);
        
    }
    
    public void expandPrices(){
        
        int currentLen = prices.length;
        double[] copyPrices = prices.clone();
        prices = new double[currentLen + 1];
        
        for(int i = 0; i<prices.length; i++){
            prices[i] = copyPrices[i];
        }
        
    }
    
    public int indexOfName(String nameProduct){
        
        return productNames.indexOf(nameProduct);
        
    }
    
    public Integer readInteger(String message, String title, int typeOfMessage){
        boolean intPass = false;
        int number = 0;

        do{
            try{
                String intMessage = JOptionPane.showInputDialog(rootPane,message ,title, typeOfMessage);

                if(intMessage == null){
                    return null;
                }
                number = Integer.parseInt(intMessage);


                if(number < 0){
                    JOptionPane.showMessageDialog(rootPane,"Solo puedes ingresar numeros positivos");
                } else {
                    intPass = true;
                }

            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Haz ingresado un numero no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } while (!intPass);

        return number;
    }
    
    public Double readDouble(String message, String title, int typeOfMessage){
        boolean doublePass = false;
        double doubleNumber = 0;

        do{
            try{
                String doubleMessage = JOptionPane.showInputDialog(rootPane,message ,title, typeOfMessage);

                if(doubleMessage == null){
                    return null;
                }
                doubleNumber = Double.parseDouble(doubleMessage);


                if(doubleNumber < 0){
                    JOptionPane.showMessageDialog(rootPane,"Solo puedes ingresar numeros positivos decimales.");
                } else {
                    doublePass = true;
                }

            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Haz ingresado un numero decimal no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } while (!doublePass);

        return doubleNumber;
    }
    
    private void buyProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyProductBtnActionPerformed
        if(productNames.size()==0){
            JOptionPane.showMessageDialog(rootPane, "No hay productos registrados", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String[] options = productNames.toArray(new String[0]);
        String selectedProduct = (String) JOptionPane.showInputDialog(rootPane, "Seleccione una opcion", "Ventana", JOptionPane.PLAIN_MESSAGE, null,options, options[0]);
        
        if(selectedProduct==null){
            return;
        }
        
        Integer quantity = readInteger("Ingrese la cantidad de producto que desea comprar","Ventana",JOptionPane.QUESTION_MESSAGE);
        if(quantity==null)return;
        
        
        
        int quantityAvailableProduct = stockProducts.get(selectedProduct);
        
        if(quantity > quantityAvailableProduct){
            JOptionPane.showMessageDialog(rootPane, "No hay suficiente stock para tu compra", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        double priceProduct = prices[indexOfProduct];
        
        int indexOfProduct = indexOfName(selectedProduct);
        
        int buyOption = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea comprar " + quantity + " cantidad del producto " + selectedProduct + " con un precio total de $" + priceProduct + " COP ?", "Confirmacion", JOptionPane.QUESTION_MESSAGE);
        
        if(buyOption == 0){
            JOptionPane.showMessageDialog(rootPane, "Haz realizado la compra exitosamente\nproducto: " + selectedProduct + "\ncantidad: " + quantity + "\nprecio: $" + priceProduct + " COP", "Exito", JOptionPane.PLAIN_MESSAGE);
        } else {
            return;
        }
    }//GEN-LAST:event_buyProductBtnActionPerformed

    private void listInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listInventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listInventoryBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        
        if(productNames.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No hay productos registrados", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double highestPrice = prices[0];
        int highestPriceIndex = 0;
        
        
        
        double lowestPrice = prices[0];
        int lowestPriceIndex = 0;
        
        
        for(int i = 0; i<productNames.size(); i++){
            if(prices[i]> highestPrice){
                highestPrice = prices[i];
                highestPriceIndex = i;
            } else if(prices[i] < lowestPrice) {
                lowestPrice = prices[i];
                lowestPriceIndex = i;
            }   
        }
        
        String highestPriceName = productNames.get(highestPriceIndex);
        String lowestPriceName = productNames.get(lowestPriceIndex);
        
        JOptionPane.showMessageDialog(rootPane, "Producto mas caro\nproducto: " + highestPriceName + "\n precio: $" + highestPrice + " COP\n\n Producto mas barato\nproducto: " + lowestPriceName + "\nprecio: $" + lowestPrice + " COP", "Reporte", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_reportsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBtn;
    private javax.swing.JButton buyProductBtn;
    private javax.swing.JButton getOutWithFinalTicketBtn;
    private javax.swing.JButton listInventoryBtn;
    private javax.swing.JButton lookProductForNameBtn;
    private javax.swing.JButton reportsBtn;
    // End of variables declaration//GEN-END:variables
}
